<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="80467" started-at="2018-01-09T03:39:52Z" finished-at="2018-01-09T03:41:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="80467" started-at="2018-01-09T03:39:52Z" finished-at="2018-01-09T03:41:12Z">
      <class name="Syn.SynechronId.TestCaseBase">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Syn.SynechronId.TestCaseBase@343f4d3d]" name="beforeTest" is-config="true" duration-ms="20358" started-at="2018-01-09T09:09:52Z" finished-at="2018-01-09T09:10:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="TestCase_1()[pri:0, instance:Syn.SynechronId.TestCaseBase@343f4d3d]" name="TestCase_1" duration-ms="60082" started-at="2018-01-09T09:10:12Z" finished-at="2018-01-09T09:11:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Syn.SynechronId.TestCaseBase.TestCase_1(TestCaseBase.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase_1 -->
        <test-method status="PASS" signature="After()[pri:0, instance:Syn.SynechronId.TestCaseBase@343f4d3d]" name="After" is-config="true" duration-ms="6" started-at="2018-01-09T09:11:12Z" finished-at="2018-01-09T09:11:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After -->
      </class> <!-- Syn.SynechronId.TestCaseBase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
